# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYK15GyXOXwCXChfnbiiLPjDjVcir7ff
"""

print("===================================")
print("      Welcome to the Quiz Game")
print("===================================")

name = input("Enter your name: ")
print("Hello,", name + "! Let's start the quiz.\n")

score = 0


answer = input("1. What is the capital of Sri Lanka? ").strip().lower()
if answer == "colombo":
    print("Correct!\n")
    score += 1
else:
    print("Wrong! The correct answer is Colombo.\n")


answer = input("2. Which programming language are you learning? ").strip().lower()
if answer == "python":
    print("Correct!\n")
    score += 1
else:
    print("Wrong! The correct answer is Python.\n")


answer = input("3. How many days are there in a week? ").strip()
if answer == "7":
    print("Correct!\n")
    score += 1
else:
    print("Wrong! The correct answer is 7.\n")

print("========================")
print("Quiz Finished!")
print("Final Score:", score, "/3")

if score == 3:
    print("Excellent! You got all answers correct.")
elif score == 2:
    print("Good job! You scored well.")
elif score == 1:
    print("Nice try! Keep practicing.")
else:
    print("Better luck next time!")

answer = input("4. What is 5 + 5? ").strip()
if answer == "10":
    print("Correct!\n")
    score += 1
else:
    print("Wrong! The correct answer is 10.\n")
